import { palette } from '@/shared/ui/mha-ui';
import { StyleSheet } from 'react-native';
export const s = StyleSheet.create({
  safe: { flex: 1, backgroundColor: palette.background, overflow: 'hidden' },
  glowTop: {
    position: 'absolute',
    width: 280,
    height: 280,
    borderRadius: 140,
    top: -145,
    right: -95,
    backgroundColor: palette.light,
    opacity: 0.45,
  },
  glowBottom: {
    position: 'absolute',
    width: 240,
    height: 240,
    borderRadius: 120,
    bottom: -145,
    left: -105,
    backgroundColor: palette.accent,
    opacity: 0.2,
  },
  content: {
    flex: 1,
    width: '100%',
    maxWidth: 520,
    alignSelf: 'center',
    paddingHorizontal: 28,
    paddingTop: 28,
    paddingBottom: 22,
  },
  progressHeader: { alignItems: 'center' },
  eyebrow: {
    fontSize: 10,
    lineHeight: 14,
    fontWeight: '800',
    letterSpacing: 1.1,
    color: palette.primary,
  },
  dots: { flexDirection: 'row', gap: 7, marginTop: 13 },
  dot: { width: 24, height: 5, borderRadius: 3, backgroundColor: palette.line },
  dotOn: { backgroundColor: palette.primary },
  hero: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingBottom: 22,
  },
  imageCard: {
    width: 208,
    height: 208,
    borderRadius: 48,
    borderWidth: 1,
    borderColor: palette.line,
    backgroundColor: palette.surface,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: palette.primaryDark,
    shadowOpacity: 0.1,
    shadowRadius: 22,
    shadowOffset: { width: 0, height: 10 },
    elevation: 4,
  },
  imageHalo: {
    position: 'absolute',
    width: 156,
    height: 156,
    borderRadius: 78,
    backgroundColor: palette.surfaceSoft,
  },
  image: { width: 150, height: 150 },
  message: {
    maxWidth: 360,
    marginTop: 34,
    fontSize: 27,
    lineHeight: 34,
    fontWeight: '800',
    letterSpacing: -0.55,
    color: palette.text,
    textAlign: 'center',
  },
  loadingRow: {
    minHeight: 34,
    marginTop: 21,
    paddingHorizontal: 14,
    borderRadius: 17,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: palette.surfaceSoft,
  },
  loadingDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: palette.secondary,
  },
  loadingText: { fontSize: 12, fontWeight: '700', color: palette.muted },
  ready: {
    marginTop: 17,
    fontSize: 13,
    lineHeight: 19,
    fontWeight: '600',
    color: palette.muted,
    textAlign: 'center',
  },
  footer: { minHeight: 52, width: '100%' },
});
