import { palette } from '@/shared/ui/mha-ui';
import { StyleSheet } from 'react-native';
export const s = StyleSheet.create({
  safe: { flex: 1, backgroundColor: palette.background },
  content: {
    width: '100%',
    maxWidth: 680,
    alignSelf: 'center',
    paddingHorizontal: 24,
    paddingTop: 28,
    paddingBottom: 112,
  },
  headingRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    marginBottom: 24,
  },
  eyebrow: {
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 1.2,
    color: palette.primary,
    marginBottom: 7,
  },
  title: {
    fontSize: 38,
    lineHeight: 42,
    fontWeight: '800',
    letterSpacing: -1,
    color: palette.text,
  },
  profileCard: {
    backgroundColor: palette.primary,
    borderRadius: 24,
    padding: 20,
    flexDirection: 'row',
    alignItems: 'center',
    overflow: 'hidden',
    shadowColor: palette.primaryDark,
    shadowOpacity: 0.24,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 6,
  },
  avatar: {
    width: 58,
    height: 58,
    borderRadius: 20,
    backgroundColor: '#E9DEFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileIcon: { width: 32, height: 32, alignItems: 'center', justifyContent: 'flex-end' },
  profileHead: {
    width: 11,
    height: 11,
    borderRadius: 6,
    backgroundColor: palette.primary,
    position: 'absolute',
    top: 1,
  },
  profileBody: {
    width: 25,
    height: 14,
    borderRadius: 14,
    backgroundColor: palette.primary,
    position: 'absolute',
    bottom: 1,
  },
  profileCopy: { flex: 1, marginLeft: 14 },
  greeting: { fontSize: 11, fontWeight: '700', color: '#D8C7FA', marginBottom: 3 },
  profileName: { fontSize: 20, fontWeight: '800', color: '#fff' },
  profileEmail: { fontSize: 12, lineHeight: 17, color: '#E9DEFF', marginTop: 3 },
  statusPill: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.16)',
    borderRadius: 20,
    paddingHorizontal: 9,
    paddingVertical: 6,
    alignSelf: 'flex-start',
  },
  statusDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: '#A8F0C8', marginRight: 5 },
  statusText: { fontSize: 10, fontWeight: '800', color: '#fff' },
  sectionLabel: {
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 1.1,
    color: palette.muted,
    marginTop: 28,
    marginBottom: 9,
  },
  card: {
    backgroundColor: '#fff',
    borderRadius: 20,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: palette.line,
    shadowColor: '#342052',
    shadowOpacity: 0.04,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  dangerCard: { borderColor: '#F1D9DF', backgroundColor: '#FFFDFD' },
  row: { minHeight: 76, flexDirection: 'row', alignItems: 'center', paddingVertical: 12 },
  rowPressed: { opacity: 0.65 },
  rowIcon: {
    width: 42,
    height: 42,
    borderRadius: 14,
    backgroundColor: '#F1EBFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  rowIconDanger: { backgroundColor: '#FBE8EC' },
  rowIconText: { fontSize: 21, fontWeight: '700', color: palette.primary },
  rowIconTextDanger: { color: palette.error },
  rowCopy: { flex: 1, marginLeft: 13, marginRight: 8 },
  rowTitle: { fontSize: 15, fontWeight: '800', color: palette.text },
  rowDescription: { fontSize: 12, lineHeight: 17, color: palette.muted, marginTop: 3 },
  chevron: { fontSize: 27, lineHeight: 28, color: '#9A90A7', fontWeight: '300' },
  dangerText: { color: palette.error },
  divider: { height: 1, backgroundColor: '#EEEAF4', marginLeft: 55 },
  sponsor: {
    fontSize: 11,
    fontWeight: '600',
    color: palette.muted,
    textAlign: 'center',
    marginTop: 34,
  },
  backdrop: {
    flex: 1,
    backgroundColor: 'rgba(32,26,43,0.52)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  dialog: { width: '100%', maxWidth: 460, borderRadius: 26, padding: 24, backgroundColor: '#fff' },
  dialogIcon: {
    width: 44,
    height: 44,
    borderRadius: 15,
    backgroundColor: '#FBE8EC',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 15,
  },
  dialogIconText: { fontSize: 22, fontWeight: '900', color: palette.error },
  dialogTitle: { fontSize: 25, fontWeight: '800', color: palette.text },
  dialogCopy: { fontSize: 14, lineHeight: 21, color: palette.muted, marginTop: 13 },
  dialogNote: { fontSize: 12, lineHeight: 18, color: palette.muted, marginTop: 10 },
  inputLabel: {
    fontSize: 13,
    fontWeight: '800',
    color: palette.text,
    marginTop: 18,
    marginBottom: 8,
  },
  input: {
    height: 54,
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: palette.accent,
    backgroundColor: '#fff',
    paddingHorizontal: 16,
    fontSize: 16,
    color: palette.text,
  },
  error: { color: palette.error, fontSize: 12, marginTop: 12 },
  cancel: { textAlign: 'center', color: palette.primary, fontWeight: '800', padding: 17 },
  deleteButton: { backgroundColor: palette.error, borderRadius: 17, padding: 16 },
  deleteButtonDisabled: { opacity: 0.45 },
  deleteText: { textAlign: 'center', color: '#fff', fontWeight: '800' },
});
