/* global __dirname, require, module, process */
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const tabs = ['pain-tracker', 'my-health', 'care-planner', 'settings'];
const mounts = [
  { source: 'auth', destination: '(auth)' },
  ...tabs.map((tab) => ({ source: tab, destination: `(main)/(${tab})` })),
];
// Shared shell and historical URLs are not another feature app directory.
const shellRoutes = [
  ['_layout.tsx', 'RootLayout', 'default'],
  ['(main)/_layout.tsx', 'MainTabs', 'default'],
  ['(legacy)/_layout.tsx', 'LegacyRoutes', 'LegacyLayout'],
  ['(legacy)/onboarding-loading.tsx', 'LegacyRoutes', 'Activation'],
  ['(legacy)/onboarding/[step].tsx', 'LegacyRoutes', 'Registration', true],
  ['(legacy)/workflow/onboarding/[step].tsx', 'LegacyRoutes', 'Registration', true],
  ['(legacy)/workflow/index.tsx', 'LegacyRoutes', 'WorkflowEntry'],
  ['(legacy)/workflow/appointment/details.tsx', 'LegacyRoutes', 'AppointmentDetails'],
  ['(legacy)/workflow/appointment/questions.tsx', 'LegacyRoutes', 'AppointmentQuestions'],
  ['(legacy)/workflow/appointment/review.tsx', 'LegacyRoutes', 'AppointmentReview'],
  ['(legacy)/workflow/prescriptions/index.tsx', 'LegacyRoutes', 'Prescriptions'],
  ['(legacy)/workflow/prescriptions/edit.tsx', 'LegacyRoutes', 'PrescriptionEditor'],
  ['(legacy)/workflow/profile.tsx', 'LegacyRoutes', 'Profile'],
  ['(legacy)/workflow/reflection.tsx', 'LegacyRoutes', 'Reflection'],
  ['(legacy)/workflow/tips.tsx', 'LegacyRoutes', 'PainGuide'],
];
const marker = '// Generated by scripts/sync-routes.cjs. Edit the owning src module instead.\n';
function walk(dir) {
  if (!fs.existsSync(dir)) return [];
  return fs
    .readdirSync(dir, { withFileTypes: true })
    .flatMap((entry) =>
      entry.isDirectory() ? walk(path.join(dir, entry.name)) : [path.join(dir, entry.name)],
    );
}
function routeFiles() {
  const result = new Map();
  for (const [destination, file, entry, dynamic] of shellRoutes) {
    const modulePath = `@/shared/navigation/${file}`;
    const exports = entry === 'default' ? 'default' : `${entry} as default`;
    result.set(
      destination,
      marker +
        `export { ${exports} } from '${modulePath}';\n` +
        (dynamic
          ? `export { registrationSteps as generateStaticParams } from '${modulePath}';\n`
          : ''),
    );
  }
  for (const mount of mounts) {
    const sourceRoot = path.join(root, 'src', mount.source);
    if (!fs.existsSync(sourceRoot)) throw new Error(`Missing route module: ${mount.source}`);
    // Source names follow feature terminology; public URLs remain backward compatible.
    const mappingFile = path.join(sourceRoot, 'route-paths.json');
    const aliases = fs.existsSync(mappingFile)
      ? JSON.parse(fs.readFileSync(mappingFile, 'utf8'))
      : {};
    const safeRoute = (name) =>
      typeof name === 'string' &&
      !path.isAbsolute(name) &&
      !name.includes('\\') &&
      !name.split('/').some((part) => part === '..' || part === '.' || !part) &&
      /\.tsx?$/.test(name);
    for (const [source, destinations] of Object.entries(aliases)) {
      if (
        !safeRoute(source) ||
        !fs.existsSync(path.join(sourceRoot, source)) ||
        !Array.isArray(destinations) ||
        !destinations.length ||
        !destinations.every(safeRoute)
      ) {
        throw new Error(`Invalid route mapping in ${mount.source}: ${source}`);
      }
    }
    for (const relative of Object.keys(aliases)) {
      const file = path.join(sourceRoot, relative);
      const destinations = aliases[relative.split(path.sep).join('/')] || [relative];
      const modulePath =
        '@/' + [mount.source, relative.replace(/\.tsx?$/, '')].join('/').split(path.sep).join('/');
      const content = fs.readFileSync(file, 'utf8');
      // A direct screen export needs no second wrapper at runtime.
      const direct = content.trim().match(/^export \{ default \} from (['"])([^'"]+)\1;$/);
      const named =
        /\bexport\s+(?:(?:async\s+)?function|const|let|var|class|interface|type|enum)\s/.test(
          content,
        );
      const body =
        direct && direct[2].startsWith('@/')
          ? content.trim() + '\n'
          : `export { default } from '${modulePath}';\n${named ? `export * from '${modulePath}';\n` : ''}`;
      for (const output of destinations) {
        const destination = path.join(mount.destination, output);
        if (result.has(destination)) throw new Error(`Duplicate generated route: ${destination}`);
        result.set(destination, marker + body);
      }
    }
  }
  return result;
}
function syncRoutes(check = false) {
  const out = path.join(root, 'app');
  const expected = routeFiles();
  let changed = 0;
  for (const [name, content] of expected) {
    const file = path.join(out, name);
    const existing = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : null;
    if (existing === content) continue;
    if (existing !== null && !existing.startsWith(marker))
      throw new Error(`Refusing to overwrite handwritten route ${file}`);
    changed++;
    if (!check) {
      fs.mkdirSync(path.dirname(file), { recursive: true });
      fs.writeFileSync(file, content);
    }
  }
  for (const file of walk(out)) {
    if (expected.has(path.relative(out, file))) continue;
    if (!fs.readFileSync(file, 'utf8').startsWith(marker))
      throw new Error(`Unexpected handwritten file in generated app/: ${file}`);
    changed++;
    if (!check) fs.unlinkSync(file);
  }
  if (check && changed) throw new Error('Route bridge is stale. Run npm run routes.');
  return expected.size;
}
module.exports = { tabs, mounts, routeFiles, syncRoutes };
if (require.main === module)
  console.log(`Route bridge ready: ${syncRoutes(process.argv.includes('--check'))} files.`);
