import { palette } from '@/shared/ui/mha-ui';
import { StyleSheet } from 'react-native';
import { s as shared } from '@/care-planner/shared/styles';
export const s = {
  ...shared,
  ...StyleSheet.create({
    recordChoicePressed: { opacity: 0.82, transform: [{ scale: 0.99 }] },
    micImage: { width: 22, height: 22, tintColor: palette.primary },
    stopIcon: { fontSize: 15, lineHeight: 18, fontWeight: '900', color: '#fff' },
    recordStatus: {
      minHeight: 38,
      marginTop: 8,
      borderRadius: 12,
      backgroundColor: '#FCECEF',
      paddingHorizontal: 12,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    liveDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: palette.error,
    },
    recordStatusText: { fontSize: 12, fontWeight: '700', color: palette.error },
    recordStatusSaved: {
      minHeight: 38,
      marginTop: 8,
      borderRadius: 12,
      backgroundColor: '#EDE5FF',
      paddingHorizontal: 12,
      justifyContent: 'center',
    },
    recordSavedText: {
      fontSize: 12,
      fontWeight: '800',
      color: palette.primaryDark,
    },
    consentScreen: { flex: 1, backgroundColor: palette.background },
    consentBack: {
      minHeight: 64,
      paddingHorizontal: 24,
      justifyContent: 'center',
    },
    consentContent: {
      width: '100%',
      maxWidth: 680,
      alignSelf: 'center',
      paddingHorizontal: 24,
      paddingTop: 4,
    },
    consentHeading: { marginBottom: 12 },
    consentEyebrow: {
      fontSize: 10,
      fontWeight: '800',
      letterSpacing: 1,
      color: palette.primary,
      marginBottom: 6,
    },
    consentTitle: {
      fontSize: 25,
      lineHeight: 31,
      fontWeight: '800',
      letterSpacing: -0.35,
      color: palette.text,
    },
    consentCard: {
      flexShrink: 1,
      backgroundColor: '#fff',
      borderWidth: 1,
      borderColor: palette.line,
      borderRadius: 20,
      paddingHorizontal: 16,
      paddingTop: 7,
      paddingBottom: 10,
    },
    consentFooter: {
      width: '100%',
      maxWidth: 680,
      alignSelf: 'center',
      paddingHorizontal: 24,
      paddingTop: 16,
      paddingBottom: 12,
    },
    signaturePad: {
      height: 96,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: '#DED5EA',
      backgroundColor: '#F3EEFF',
      overflow: 'hidden',
      position: 'relative',
    },
    signatureHint: {
      position: 'absolute',
      left: 0,
      right: 0,
      top: 38,
      textAlign: 'center',
      fontSize: 13,
      color: palette.muted,
    },
    clearSignature: {
      alignSelf: 'flex-end',
      paddingVertical: 3,
      paddingHorizontal: 4,
    },
    clearSignatureText: {
      fontSize: 12,
      fontWeight: '700',
      color: palette.primary,
    },
    recordChoice: {
      minHeight: 60,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      marginTop: 14,
      borderRadius: 16,
      backgroundColor: '#fff',
      borderWidth: 1,
      borderColor: '#DED5EA',
      paddingHorizontal: 12,
      paddingVertical: 8,
      shadowColor: '#32165C',
      shadowOpacity: 0.035,
      shadowRadius: 6,
      shadowOffset: { width: 0, height: 2 },
    },
    mic: {
      width: 42,
      height: 42,
      borderRadius: 14,
      backgroundColor: '#D8C7FA',
      alignItems: 'center',
      justifyContent: 'center',
    },
    recordText: {
      flex: 1,
      fontSize: 13,
      lineHeight: 18,
      fontWeight: '800',
      color: palette.primaryDark,
    },
    fieldLabel: {
      fontSize: 11,
      lineHeight: 16,
      fontWeight: '700',
      color: palette.text,
      marginTop: 8,
      marginBottom: 4,
    },
    readonly: {
      minHeight: 39,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: '#DED5EA',
      backgroundColor: '#FAF9FC',
      paddingHorizontal: 14,
      justifyContent: 'center',
    },
    legal: {
      fontSize: 10,
      lineHeight: 14,
      color: palette.muted,
      marginTop: 2,
      paddingHorizontal: 2,
    },
  }),
};
