/** Defines the colors, spacing, and layout used by account setup / welcome page. */
import { palette } from '@/constants/profile/ui';
import { StyleSheet } from 'react-native';
export const s = StyleSheet.create({
  safe: { flex: 1, backgroundColor: '#fff' },
  page: { paddingHorizontal: 24 },
  art: {
    height: 294,
    alignItems: 'center',
    justifyContent: 'flex-start',
    overflow: 'hidden',
  },
  message: {
    width: '100%',
    maxWidth: 520,
    alignSelf: 'center',
    minHeight: 104,
    fontSize: 28,
    lineHeight: 35,
    fontWeight: '800',
    letterSpacing: -0.65,
    color: palette.text,
    paddingHorizontal: 18,
    marginTop: 10,
    marginBottom: 8,
  },
  dots: {
    width: '100%',
    maxWidth: 520,
    height: 48,
    alignSelf: 'center',
    paddingHorizontal: 18,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    gap: 8,
  },
  dot: { width: 12, height: 12, borderRadius: 6, backgroundColor: '#D8CFE5' },
  dotOn: { width: 34, height: 12, borderRadius: 6, backgroundColor: '#5E17EB' },
  actions: {
    width: '100%',
    maxWidth: 520,
    alignSelf: 'center',
    paddingHorizontal: 30,
    gap: 6,
  },
  primary: {
    height: 50,
    borderRadius: 9,
    backgroundColor: '#5E17EB',
    alignItems: 'center',
    justifyContent: 'center',
  },
  primaryPressed: { backgroundColor: '#4610B8', transform: [{ scale: 0.99 }] },
  primaryText: { fontSize: 14, fontWeight: '800', color: '#fff' },
  secondary: { height: 40, alignItems: 'center', justifyContent: 'center' },
  secondaryPressed: { backgroundColor: '#F3EEFF', borderRadius: 12 },
  secondaryText: {
    fontSize: 13,
    fontWeight: '700',
    textDecorationLine: 'underline',
    color: '#201A2B',
  },
  sponsor: {
    fontSize: 10,
    fontWeight: '500',
    color: '#686173',
    textAlign: 'center',
    paddingTop: 8,
    paddingBottom: 14,
  },
});
