/** Defines the splash carousel layout; shared account forms use auth-ui.tsx. */
import { palette } from '@/constants/profile/ui';
import { StyleSheet } from 'react-native';
export const s = StyleSheet.create({
  safe: { flex: 1, backgroundColor: palette.surface },
  list: { backgroundColor: palette.background },
  page: { paddingHorizontal: 24, backgroundColor: palette.background },
  art: {
    height: 294,
    alignItems: 'center',
    justifyContent: 'flex-start',
    overflow: 'hidden',
  },
  message: {
    width: '100%',
    maxWidth: 520,
    alignSelf: 'center',
    minHeight: 104,
    fontSize: 28,
    lineHeight: 35,
    fontWeight: '800',
    letterSpacing: -0.65,
    color: palette.text,
    paddingHorizontal: 18,
    marginTop: 10,
    marginBottom: 8,
  },
  dots: {
    width: '100%',
    maxWidth: 520,
    height: 48,
    alignSelf: 'center',
    paddingHorizontal: 18,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    gap: 8,
  },
  dot: { width: 12, height: 12, borderRadius: 6, backgroundColor: palette.light },
  dotOn: { width: 34, height: 12, borderRadius: 6, backgroundColor: palette.success },
  actions: {
    width: '100%',
    maxWidth: 520,
    alignSelf: 'center',
    paddingHorizontal: 30,
    gap: 6,
    backgroundColor: palette.background,
  },
  primary: {
    height: 50,
    borderRadius: 9,
    backgroundColor: palette.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  primaryPressed: { backgroundColor: palette.primaryDark, transform: [{ scale: 0.99 }] },
  primaryText: { fontSize: 14, fontWeight: '800', color: palette.text },
  secondary: { height: 40, alignItems: 'center', justifyContent: 'center' },
  secondaryPressed: { backgroundColor: palette.pressedBackground, borderRadius: 12 },
  secondaryText: {
    fontSize: 13,
    fontWeight: '700',
    textDecorationLine: 'underline',
    color: palette.text,
  },
  sponsor: {
    fontSize: 10,
    fontWeight: '500',
    color: palette.muted,
    textAlign: 'center',
    paddingTop: 8,
    paddingBottom: 28,
    backgroundColor: palette.background,
  },
});
