import { palette } from '@/shared/ui/mha-ui';
import { StyleSheet } from 'react-native';
export const s = StyleSheet.create({
  printError: { color: '#A52035', fontSize: 12, maxWidth: 160, marginTop: 6 },
  empty: { marginTop: 24, paddingVertical: 24 },
  emptyCopy: { fontSize: 13, lineHeight: 20, color: palette.muted },
  tableHeading: { fontWeight: '700', backgroundColor: '#F3EEFF' },
  overlay: {
    flex: 1,
    backgroundColor: '#00000066',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  dropdown: {
    width: '100%',
    maxWidth: 520,
    maxHeight: '80%',
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    padding: 20,
  },
  dropdownList: { flexShrink: 1, marginTop: 12 },
  dropdownOption: {
    minHeight: 58,
    padding: 12,
    borderRadius: 10,
    marginBottom: 6,
    borderWidth: 1,
    borderColor: palette.line,
  },
  dropdownSelected: { backgroundColor: '#F3EEFF', borderColor: palette.primary },
  optionLabel: { color: palette.text, fontSize: 14, fontWeight: '700', lineHeight: 21 },
  chartFrame: {
    marginTop: 14,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: palette.line,
    borderRadius: 12,
    overflow: 'hidden',
  },
  safe: { flex: 1, backgroundColor: '#fff' },
  content: {
    width: '100%',
    maxWidth: 680,
    alignSelf: 'center',
    paddingHorizontal: 24,
    paddingTop: 10,
    paddingBottom: 120,
  },
  back: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '700',
    color: palette.primary,
    paddingVertical: 12,
  },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  title: {
    flex: 1,
    fontSize: 21,
    lineHeight: 27,
    fontWeight: '800',
    color: palette.text,
  },
  print: {
    minHeight: 42,
    borderRadius: 14,
    paddingHorizontal: 10,
    paddingVertical: 7,
    backgroundColor: palette.primary,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    shadowColor: palette.primaryDark,
    shadowOpacity: 0.18,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
  },
  printPressed: {
    backgroundColor: palette.primaryDark,
    transform: [{ scale: 0.97 }],
  },
  printLoading: { opacity: 0.72 },
  pdfBadge: {
    height: 26,
    minWidth: 30,
    borderRadius: 8,
    backgroundColor: palette.light,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 5,
  },
  pdfBadgeText: {
    fontSize: 8,
    fontWeight: '900',
    letterSpacing: 0.4,
    color: palette.primaryDark,
  },
  printText: { fontSize: 11, fontWeight: '800', color: '#fff' },
  tabs: {
    height: 48,
    backgroundColor: '#F3EEFF',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: palette.line,
    overflow: 'hidden',
    flexDirection: 'row',
    marginTop: 20,
  },
  tab: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    borderBottomWidth: 2,
    borderBottomColor: 'transparent',
  },
  tabOn: { borderBottomColor: palette.primary },
  tabText: { fontSize: 12, color: palette.text },
  tabTextOn: { fontWeight: '800', color: palette.primary },
  chartHead: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 12,
    flexWrap: 'wrap',
    gap: 10,
  },
  metricTitle: { fontSize: 18, fontWeight: '700', color: palette.text },
  filter: {
    minHeight: 44,
    maxWidth: '100%',
    flexShrink: 1,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: palette.line,
    borderRadius: 17,
    paddingHorizontal: 14,
    justifyContent: 'center',
  },
  filterText: { fontSize: 11, color: palette.text },
  chart: {
    height: 190,
    backgroundColor: '#fff',
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
    flexDirection: 'row',
    alignItems: 'flex-end',
    borderLeftWidth: 1,
    borderBottomWidth: 1,
    borderColor: palette.line,
    marginTop: 14,
    overflow: 'hidden',
  },
  chartColumn: {
    flex: 1,
    height: '100%',
    justifyContent: 'flex-end',
    position: 'relative',
  },
  area: {
    backgroundColor: '#F3EEFF',
    borderTopWidth: 2,
    borderTopColor: palette.secondary,
  },
  point: {
    position: 'absolute',
    alignSelf: 'center',
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: palette.primary,
  },
  axis: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 6 },
  axisText: { fontSize: 7, color: palette.muted },
  segment: {
    height: 34,
    flexDirection: 'row',
    borderWidth: 1,
    borderColor: palette.line,
    borderRadius: 17,
    overflow: 'hidden',
    marginTop: 18,
  },
  segmentItem: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  segmentOn: { backgroundColor: '#F3EEFF' },
  segmentText: { fontSize: 11, color: palette.text },
  segmentTextOn: { fontWeight: '800', color: palette.primaryDark },
  table: {
    marginTop: 16,
    borderWidth: 1,
    borderColor: palette.line,
    borderRadius: 12,
    overflow: 'hidden',
    backgroundColor: '#fff',
  },
  tableRow: {
    minHeight: 34,
    flexDirection: 'row',
    borderTopWidth: 1,
    borderTopColor: palette.line,
  },
  tableFirst: { borderTopWidth: 0 },
  cell: {
    flex: 1,
    fontSize: 10,
    textAlign: 'center',
    textAlignVertical: 'center',
    color: palette.text,
    padding: 7,
  },
  dateCell: { flex: 1.35, textAlign: 'left' },
  more: {
    height: 44,
    borderRadius: 12,
    backgroundColor: '#F3EEFF',
    borderWidth: 1,
    borderColor: palette.line,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 16,
  },
  moreText: { fontSize: 11, fontWeight: '800', color: palette.text },
  history: { marginTop: 14 },
  historyGroup: {
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: palette.line,
  },
  historyDate: {
    fontSize: 14,
    fontWeight: '800',
    color: palette.text,
    marginBottom: 8,
  },
  historyItem: { fontSize: 13, lineHeight: 27, color: palette.text },
  historyArrow: { color: palette.primary },
});
