import { palette } from '@/shared/ui/mha-ui';
import { StyleSheet } from 'react-native';
export const s = StyleSheet.create({
  detailRow: {
    minHeight: 66,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#E3D9F6',
  },
  detailRowLast: { borderBottomWidth: 0 },
  detailMark: {
    width: 36,
    height: 36,
    borderRadius: 12,
    backgroundColor: '#D8C7FA',
    alignItems: 'center',
    justifyContent: 'center',
  },
  detailMarkText: {
    fontSize: 10,
    fontWeight: '900',
    color: palette.primaryDark,
  },
  detailCopy: { flex: 1 },
  answerHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    marginBottom: 10,
  },
  answerPill: {
    minHeight: 28,
    borderRadius: 14,
    backgroundColor: '#D8C7FA',
    paddingHorizontal: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  answerPillSaved: { backgroundColor: '#E9DEFF' },
  answerLabelSaved: { color: palette.primaryDark },
  editCircle: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#DED5EA',
    alignItems: 'center',
    justifyContent: 'center',
  },
  noQuestions: {
    minHeight: 54,
    marginTop: 10,
    borderRadius: 14,
    backgroundColor: '#F3EEFF',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  noQuestionsText: { fontSize: 13, fontWeight: '600', color: palette.muted },
  recordChoiceOn: { backgroundColor: '#FCECEF', borderColor: '#E9B7C2' },
  recordTextOn: { color: palette.error },
  micOn: { backgroundColor: palette.error },
  step: {
    fontSize: 12,
    lineHeight: 18,
    fontWeight: '800',
    letterSpacing: 0.5,
    color: palette.primary,
    marginTop: 8,
  },
  planFooter: { marginTop: 22 },
  safe: { flex: 1, backgroundColor: palette.background },
  content: {
    width: '100%',
    maxWidth: 680,
    alignSelf: 'center',
    paddingHorizontal: 24,
    paddingTop: 14,
    paddingBottom: 120,
  },
  back: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '700',
    color: palette.primary,
    paddingVertical: 12,
  },
  title: {
    fontSize: 27,
    lineHeight: 34,
    fontWeight: '800',
    letterSpacing: -0.45,
    color: palette.text,
  },
  plan: {
    marginTop: 20,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#E5DFF0',
    borderRadius: 22,
    padding: 18,
    shadowColor: '#32165C',
    shadowOpacity: 0.055,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 5 },
    elevation: 2,
  },
  cardTitle: {
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '800',
    color: palette.text,
  },
  overview: {
    backgroundColor: '#F7F4FC',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#E8E0F3',
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 16,
    marginTop: 14,
  },
  metaLabel: {
    fontSize: 11,
    lineHeight: 16,
    fontWeight: '800',
    color: palette.primaryDark,
    marginTop: 12,
  },
  metaValue: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '600',
    color: palette.text,
    marginTop: 2,
  },
  questionsTitle: {
    fontSize: 17,
    lineHeight: 23,
    fontWeight: '800',
    color: palette.text,
    marginTop: 26,
  },
  consentRow: {
    minHeight: 48,
    borderRadius: 14,
    backgroundColor: '#F3EEFF',
    borderWidth: 1,
    borderColor: 'transparent',
    paddingHorizontal: 13,
    paddingVertical: 9,
    marginTop: 10,
    flexDirection: 'row',
    alignItems: 'center',
  },
  consentRowOn: {
    backgroundColor: '#EDE5FF',
    borderColor: palette.accent,
    shadowColor: palette.primary,
    shadowOpacity: 0.1,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  consentCopy: { flex: 1, paddingRight: 10 },
  consentText: {
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '700',
    color: palette.text,
  },
  consentTextOn: {
    fontSize: 13,
    fontWeight: '800',
    color: palette.primaryDark,
  },
  consentMeta: {
    fontSize: 10,
    lineHeight: 14,
    fontWeight: '600',
    color: palette.muted,
    marginTop: 2,
  },
  check: {
    width: 22,
    height: 22,
    borderRadius: 5,
    borderWidth: 1.5,
    borderColor: palette.muted,
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkOn: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: palette.primary,
    borderColor: palette.primary,
  },
  checkMark: { fontSize: 13, fontWeight: '800', color: '#fff' },
  group: { marginTop: 22, gap: 10 },
  groupTitle: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '800',
    color: palette.primaryDark,
    paddingHorizontal: 2,
  },
  question: {
    minHeight: 104,
    borderRadius: 16,
    backgroundColor: '#F7F4FC',
    borderWidth: 1,
    borderColor: '#E8E0F3',
    padding: 15,
    flexDirection: 'row',
    alignItems: 'flex-start',
    shadowColor: '#32165C',
    shadowOpacity: 0.025,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
  },
  questionCopy: { flex: 1 },
  answerLabel: {
    fontSize: 10,
    lineHeight: 14,
    fontWeight: '800',
    letterSpacing: 0.2,
    color: palette.primary,
    marginBottom: 7,
  },
  questionText: { fontSize: 14, lineHeight: 21, color: palette.text },
  edit: { fontSize: 19, color: palette.primaryDark, marginLeft: 10 },
  micText: { fontSize: 16, color: '#fff' },
  ok: { fontSize: 14, fontWeight: '800', color: palette.primary },
  consentModal: { backgroundColor: '#fff', borderRadius: 22, padding: 20 },
  signature: {
    minHeight: 92,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: palette.line,
    backgroundColor: '#F4F2F7',
    padding: 13,
    textAlignVertical: 'top',
  },
  consentActions: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 18,
    marginTop: 18,
  },
  save: { width: 160 },
});
