export const sexOptions = ['Female', 'Male', 'Intersex', 'Prefer not to say'];
export const diagnosisOptions = ['Yes, I have', 'No, I haven’t'];
export const painConditions = [
  'Arthritis',
  'Ankylosing spondylitis',
  'Back pain',
  'Baker’s cyst',
  'Bursitis',
  'Foot related conditions',
  'Fibromyalgia',
  'Gout',
  'Juvenile idiopathic arthritis and conditions',
  'Lupus',
  'Neck pain',
  'Osteoarthritis',
  'Osteoporosis',
  'Paget’s disease',
  'Perthes’ disease',
  'Polymyalgia rheumatica',
  'Psoriatic arthritis',
  'Raynaud’s phenomenon',
  'Reactive arthritis',
  'Rheumatoid arthritis',
  'Scleroderma',
  'Shoulder pain',
  'Sjogren’s disease',
];
