import { palette } from '@/shared/ui/mha-ui';
import { StyleSheet } from 'react-native';
export const s = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: palette.background,
  },
  content: {
    width: '100%',
    maxWidth: 680,
    alignSelf: 'center',
    paddingHorizontal: 24,
    paddingTop: 20,
    paddingBottom: 120,
  },
  top: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  back: {
    fontSize: 14,
    fontWeight: '700',
    color: palette.primary,
    paddingVertical: 12,
  },
  counter: {
    fontSize: 12,
    fontWeight: '700',
    color: palette.muted,
  },
  track: {
    height: 5,
    borderRadius: 4,
    backgroundColor: '#E9E3EC',
    overflow: 'hidden',
    marginTop: 8,
    marginBottom: 26,
  },
  fill: {
    height: '100%',
    borderRadius: 4,
    backgroundColor: palette.secondary,
  },
  module: {
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 1.1,
    color: palette.primary,
    textTransform: 'uppercase',
  },
  title: {
    fontSize: 28,
    lineHeight: 34,
    fontWeight: '800',
    letterSpacing: -0.6,
    color: palette.text,
    marginTop: 8,
  },
  prompt: {
    fontSize: 15,
    lineHeight: 22,
    color: palette.muted,
    marginTop: 9,
  },
  helper: {
    fontSize: 12,
    lineHeight: 18,
    color: palette.muted,
    marginTop: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
    backgroundColor: palette.surfaceSoft,
    borderRadius: 12,
  },
  options: {
    gap: 12,
    marginTop: 24,
  },
  option: {
    minHeight: 64,
    borderRadius: 17,
    borderWidth: 1,
    borderColor: palette.line,
    backgroundColor: '#fff',
    paddingHorizontal: 18,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
  },
  optionOn: {
    backgroundColor: '#F3EEFF',
    borderColor: '#BEA1F7',
  },
  optionText: {
    flex: 1,
    fontSize: 14,
    lineHeight: 20,
    color: palette.text,
    paddingRight: 10,
  },
  optionTextOn: {
    fontWeight: '700',
    color: palette.primaryDark,
  },
  box: {
    width: 24,
    height: 24,
    borderWidth: 1.5,
    borderColor: '#B9AFC8',
    borderRadius: 7,
    alignItems: 'center',
    justifyContent: 'center',
  },
  radio: {
    width: 24,
    height: 24,
    borderWidth: 1.5,
    borderColor: '#B9AFC8',
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  markOn: {
    backgroundColor: palette.primary,
    borderColor: palette.primary,
  },
  tick: {
    color: '#fff',
    fontSize: 13,
    fontWeight: '800',
  },
  score: {
    backgroundColor: '#F7F4FC',
    borderRadius: 24,
    padding: 24,
    alignItems: 'center',
    marginTop: 26,
  },
  scoreNumber: {
    fontSize: 38,
    fontWeight: '800',
    color: palette.primaryDark,
  },
  scoreLabel: {
    fontSize: 13,
    color: palette.muted,
    marginTop: 7,
  },
  sliderArea: { marginTop: 28, marginBottom: 12 },
  sliderTrack: {
    height: 30,
    borderRadius: 15,
    backgroundColor: '#D8C7FA',
    justifyContent: 'center',
  },
  sliderFill: {
    position: 'absolute',
    left: 0,
    height: 18,
    borderRadius: 9,
    backgroundColor: '#5E17EB',
  },
  sliderThumb: {
    position: 'absolute',
    marginLeft: -10,
    width: 20,
    height: 42,
    borderRadius: 6,
    backgroundColor: '#5E17EB',
    alignItems: 'center',
  },
  sliderBubble: {
    position: 'absolute',
    top: -40,
    minWidth: 42,
    height: 34,
    borderRadius: 7,
    backgroundColor: '#5E17EB',
    alignItems: 'center',
    justifyContent: 'center',
  },
  sliderBubbleText: { fontSize: 16, fontWeight: '800', color: '#fff' },
  sliderEnds: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 9,
  },
  sliderEnd: { fontSize: 11, fontWeight: '700', color: palette.muted },
  numbers: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: 8,
    marginTop: 20,
  },
  number: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: palette.line,
    alignItems: 'center',
    justifyContent: 'center',
  },
  numberOn: {
    backgroundColor: palette.primary,
    borderColor: palette.primary,
  },
  numberText: {
    fontSize: 14,
    fontWeight: '700',
    color: palette.text,
  },
  numberTextOn: {
    color: '#fff',
  },
  input: {
    minHeight: 58,
    borderWidth: 1,
    borderColor: palette.line,
    borderRadius: 18,
    backgroundColor: '#fff',
    padding: 16,
    fontSize: 15,
    color: palette.text,
    textAlignVertical: 'top',
    marginTop: 24,
  },
  action: {
    marginTop: 28,
  },
  required: {
    fontSize: 12,
    fontWeight: '400',
    color: palette.text,
    textAlign: 'center',
    marginTop: 10,
  },
  summary: {
    width: '100%',
    maxWidth: 680,
    alignSelf: 'center',
    paddingHorizontal: 24,
    paddingTop: 24,
    paddingBottom: 110,
  },
  period: {
    fontSize: 12,
    lineHeight: 20,
    fontWeight: '700',
    color: palette.primary,
  },
  summaryTitle: {
    fontSize: 30,
    fontWeight: '800',
    color: palette.text,
    marginTop: 8,
  },
  summaryCopy: {
    fontSize: 15,
    lineHeight: 22,
    color: palette.muted,
    marginTop: 8,
  },
  resultCard: {
    backgroundColor: palette.surface,
    borderRadius: 22,
    padding: 20,
    marginVertical: 24,
  },
  summaryMeta: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingBottom: 14,
    marginBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: palette.line,
  },
  resultSection: { paddingVertical: 10 },
  resultLabel: {
    fontSize: 13,
    fontWeight: '800',
    color: palette.text,
    marginBottom: 5,
  },
  painSection: {
    paddingTop: 18,
    paddingBottom: 16,
    borderTopWidth: 1,
    borderTopColor: palette.line,
  },
  painSectionFirst: { borderTopWidth: 0, paddingTop: 8 },
  painSectionTitle: {
    fontSize: 16,
    lineHeight: 21,
    fontWeight: '800',
    letterSpacing: -0.2,
    color: palette.primaryDark,
    marginBottom: 10,
  },
  resultValue: {
    fontSize: 13,
    lineHeight: 20,
    color: palette.text,
    fontWeight: '600',
    marginTop: 5,
  },
  intensityItem: {
    paddingTop: 10,
    paddingLeft: 12,
    borderLeftWidth: 2,
    borderLeftColor: palette.accent,
    marginTop: 2,
  },
  intensityLabel: {
    fontSize: 13,
    lineHeight: 19,
    fontWeight: '700',
    color: palette.text,
    marginBottom: 2,
  },
  summaryStatement: {
    backgroundColor: '#F3EEFF',
    paddingHorizontal: 18,
    paddingVertical: 22,
  },
  summaryInsight: {
    marginBottom: 20,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: palette.accent,
    overflow: 'hidden',
  },
  summaryStatementText: {
    fontSize: 14,
    lineHeight: 21,
    fontWeight: '600',
    color: palette.text,
    textAlign: 'center',
  },
  guideButton: {
    minHeight: 54,
    backgroundColor: palette.light,
    borderTopWidth: 1,
    borderTopColor: palette.accent,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
  },
  guidePressed: { backgroundColor: palette.accent },
  guideIcon: { fontSize: 19, fontWeight: '800', color: palette.primary },
  guideText: { fontSize: 13, fontWeight: '800', color: palette.primaryDark },
  guideArrow: { fontSize: 22, color: palette.primary },
  summaryFooter: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 16,
  },
  closeButton: {
    minWidth: 96,
    minHeight: 42,
    borderRadius: 21,
    borderWidth: 1,
    borderColor: palette.line,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 20,
  },
  closePressed: { backgroundColor: '#F2EDFA' },
  closeText: { fontSize: 13, fontWeight: '800', color: palette.text },
  resultHeading: {
    fontSize: 16,
    fontWeight: '800',
    color: palette.text,
    marginBottom: 10,
  },
  headingDivider: {
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: palette.line,
  },
  result: {
    fontSize: 13,
    lineHeight: 20,
    color: palette.text,
    marginBottom: 5,
  },
  saved: {
    fontSize: 12,
    fontWeight: '700',
    color: '#27705A',
    textAlign: 'left',
    marginBottom: 0,
    flex: 1,
  },
});
