import { palette } from '@/shared/ui/mha-ui';
import { StyleSheet } from 'react-native';
export const s = StyleSheet.create({
  safe: { flex: 1, backgroundColor: palette.background },
  center: { flex: 1, justifyContent: 'center' },
  loading: { textAlign: 'center', fontSize: 15, color: palette.muted },
  content: {
    width: '100%',
    maxWidth: 520,
    alignSelf: 'center',
    paddingHorizontal: 28,
    paddingVertical: 32,
  },
  backButton: { alignSelf: 'flex-start', marginBottom: 22 },
  back: {
    fontSize: 14,
    fontWeight: '700',
    color: palette.primary,
    paddingVertical: 8,
  },
  intro: { marginBottom: 30 },
  eyebrow: {
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 1.15,
    color: palette.primary,
    marginBottom: 10,
  },
  title: {
    fontSize: 30,
    lineHeight: 36,
    fontWeight: '800',
    letterSpacing: -0.65,
    color: palette.text,
  },
  copy: { fontSize: 15, lineHeight: 22, color: palette.muted, marginTop: 8 },
  form: { width: '100%' },
  label: {
    fontSize: 13,
    fontWeight: '800',
    color: palette.text,
    marginBottom: 8,
  },
  input: {
    height: 58,
    borderRadius: 18,
    borderWidth: 1.5,
    borderColor: palette.accent,
    backgroundColor: '#fff',
    paddingHorizontal: 18,
    fontSize: 18,
    fontWeight: '700',
    color: palette.text,
    letterSpacing: 1,
  },
  help: { fontSize: 12, lineHeight: 18, color: palette.muted, marginTop: 9 },
  inlineLink: { alignSelf: 'flex-end', paddingVertical: 11, paddingLeft: 16 },
  inlineLinkText: {
    fontSize: 13,
    fontWeight: '700',
    color: palette.primary,
    textDecorationLine: 'underline',
  },
  action: { marginTop: 18 },
  accountSwitch: { marginTop: 22, alignItems: 'center' },
  accountButton: {
    minHeight: 40,
    paddingHorizontal: 16,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 12,
  },
  accountButtonPressed: { backgroundColor: palette.surfaceSoft },
  accountLink: { fontSize: 12.5, fontWeight: '600', color: palette.muted },
  modalBackdrop: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
    backgroundColor: 'rgba(32,26,43,0.52)',
  },
  dialog: { width: '100%', maxWidth: 440, borderRadius: 24, padding: 24, backgroundColor: '#fff' },
  dialogTitle: { fontSize: 24, fontWeight: '800', color: palette.text },
  dialogCopy: { fontSize: 15, lineHeight: 22, color: palette.muted, marginVertical: 18 },
});
