/** Defines the colors, spacing, and layout used by Pain Tracker / overview. */
import { palette } from '@/constants/profile/ui';
import { StyleSheet } from 'react-native';
export const s = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: palette.surface,
  },
  body: { flex: 1, backgroundColor: palette.background },
  content: {
    width: '100%',
    maxWidth: 680,
    alignSelf: 'center',
    paddingHorizontal: 24,
    paddingTop: 24,
    paddingBottom: 112,
  },
  banner: {
    backgroundColor: 'transparent',
    paddingVertical: 4,
  },
  greeting: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '600',
    color: palette.text,
  },
  bannerTitle: {
    fontSize: 21,
    lineHeight: 27,
    fontWeight: '800',
    letterSpacing: -0.35,
    color: palette.text,
    marginTop: 0,
  },
  bannerTitleRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 5,
    marginTop: 10,
    flexWrap: 'wrap',
  },
  brandWord: { width: 69, height: 27, position: 'relative' },
  brandM: {
    position: 'absolute',
    left: 0,
    bottom: 0,
    fontSize: 24,
    lineHeight: 27,
    fontWeight: '800',
    color: palette.text,
  },
  brandPowered: {
    position: 'absolute',
    left: 20,
    top: 0,
    fontSize: 11,
    lineHeight: 13,
    fontWeight: '800',
    color: palette.text,
  },
  streak: {
    minHeight: 58,
    marginTop: 14,
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderWidth: 1,
    borderColor: palette.light,
    borderRadius: 16,
    backgroundColor: palette.selectionBackground,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  streakIcon: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: palette.light,
    alignItems: 'center',
    justifyContent: 'center',
  },
  streakSpark: {
    fontSize: 19,
    color: palette.success,
  },
  streakValue: {
    fontSize: 14,
    lineHeight: 18,
    fontWeight: '800',
    color: palette.text,
  },
  streakLabel: {
    marginTop: 1,
    fontSize: 10,
    lineHeight: 14,
    color: palette.muted,
  },
  streakEncouragement: {
    marginLeft: 'auto',
    fontSize: 11,
    fontWeight: '700',
    color: palette.success,
  },
  bannerCopy: {
    fontSize: 14,
    lineHeight: 20,
    color: palette.muted,
    marginTop: 8,
  },
  progressHead: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 9,
  },
  progressBlock: { marginTop: 24, marginBottom: 28 },
  progressLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: palette.text,
  },
  progressCount: {
    fontSize: 12,
    fontWeight: '600',
    color: palette.muted,
  },
  track: {
    height: 10,
    borderRadius: 5,
    backgroundColor: palette.line,
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowRadius: 3,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    overflow: 'hidden',
  },
  trackFill: {
    height: '100%',
    borderRadius: 5,
    backgroundColor: palette.success,
  },
  sectionTitle: {
    fontSize: 17,
    fontWeight: '800',
    color: palette.text,
    marginBottom: 6,
    marginLeft: 2,
  },
  panel: {
    backgroundColor: palette.surface,
    borderRadius: 20,
    padding: 16,
    gap: 12,
  },
  assessment: {
    height: 72,
    borderRadius: 16,
    backgroundColor: palette.accentSoft,
    paddingHorizontal: 18,
    paddingVertical: 0,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: palette.accent,
  },
  pressed: {
    opacity: 0.82,
    transform: [
      {
        scale: 0.99,
      },
    ],
  },
  assessmentTitle: {
    fontSize: 15,
    lineHeight: 20,
    fontWeight: '600',
    color: palette.text,
  },
  assessmentCopy: {
    position: 'absolute',
    left: 18,
    right: 132,
    top: 0,
    bottom: 0,
    justifyContent: 'center',
  },
  updated: { fontSize: 11, lineHeight: 15, color: palette.muted, marginTop: 2 },
  record: {
    position: 'absolute',
    right: 18,
    top: 17,
    height: 38,
    borderWidth: 1,
    borderColor: palette.primary,
    backgroundColor: palette.primary,
    borderRadius: 17,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  recordText: {
    fontSize: 12,
    fontWeight: '700',
    color: palette.text,
  },
  arrow: {
    fontSize: 18,
    lineHeight: 18,
    color: palette.text,
  },
  sponsor: {
    fontSize: 11,
    fontWeight: '600',
    color: palette.muted,
    textAlign: 'center',
    marginTop: 24,
  },
});
