/** Defines the colors, spacing, and layout used by Settings / privacy and permissions. */
import { palette } from '@/shared/ui/mha-ui';
import { StyleSheet } from 'react-native';
export const s = StyleSheet.create({
  safe: { flex: 1, backgroundColor: palette.background },
  content: {
    width: '100%',
    maxWidth: 680,
    alignSelf: 'center',
    paddingHorizontal: 24,
    paddingTop: 16,
    paddingBottom: 112,
  },
  back: { color: palette.primary, fontSize: 14, fontWeight: '700', paddingVertical: 14 },
  eyebrow: {
    color: palette.primary,
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 1.15,
    marginTop: 8,
  },
  title: {
    color: palette.text,
    fontSize: 34,
    lineHeight: 40,
    fontWeight: '800',
    letterSpacing: -0.8,
    marginTop: 6,
  },
  intro: { color: palette.muted, fontSize: 15, lineHeight: 23, marginTop: 10, marginBottom: 22 },
  notice: {
    flexDirection: 'row',
    backgroundColor: '#EAF7F0',
    borderRadius: 20,
    padding: 17,
    borderWidth: 1,
    borderColor: '#CBEBD9',
  },
  noticeIcon: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#257A57',
    color: '#fff',
    textAlign: 'center',
    lineHeight: 28,
    fontWeight: '800',
  },
  noticeCopy: { flex: 1, marginLeft: 12 },
  noticeTitle: { color: '#1E6247', fontSize: 14, fontWeight: '800' },
  noticeText: { color: '#39725A', fontSize: 12, lineHeight: 18, marginTop: 4 },
  label: {
    color: palette.muted,
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 1.1,
    marginTop: 28,
    marginBottom: 9,
  },
  card: {
    backgroundColor: '#fff',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: palette.line,
    paddingHorizontal: 16,
  },
  permissionRow: { flexDirection: 'row', alignItems: 'center', minHeight: 82, paddingVertical: 12 },
  permissionIcon: {
    width: 40,
    height: 40,
    borderRadius: 13,
    backgroundColor: '#F1EBFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  permissionIconText: { color: palette.primary, fontSize: 19 },
  permissionCopy: { flex: 1, marginLeft: 12, marginRight: 8 },
  permissionTitle: { color: palette.text, fontSize: 14, fontWeight: '800' },
  permissionDescription: { color: palette.muted, fontSize: 12, lineHeight: 17, marginTop: 3 },
  permissionStatus: { color: palette.primary, fontSize: 10, fontWeight: '800' },
  divider: { height: 1, backgroundColor: '#EEEAF4', marginLeft: 52 },
  policyCard: {
    backgroundColor: '#fff',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: palette.line,
    padding: 18,
  },
  lastUpdated: { color: palette.muted, fontSize: 11, fontWeight: '700', marginBottom: 5 },
  section: { marginTop: 17 },
  sectionTitle: { color: palette.text, fontSize: 14, fontWeight: '800' },
  sectionBody: { color: palette.muted, fontSize: 13, lineHeight: 20, marginTop: 5 },
  link: { color: palette.primary, fontSize: 13, lineHeight: 19, fontWeight: '800', marginTop: 20 },
  footerNote: {
    color: palette.muted,
    fontSize: 11,
    lineHeight: 17,
    textAlign: 'center',
    marginTop: 18,
  },
});
