import { s as common } from '@/shared/forms/styles';
import { palette } from '@/shared/ui/mha-ui';
import { StyleSheet } from 'react-native';
export const s = {
  ...common,
  ...StyleSheet.create({
    dateField: {
      minHeight: 56,
      borderRadius: 17,
      borderWidth: 1,
      borderColor: palette.line,
      backgroundColor: '#fff',
      paddingHorizontal: 16,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    dateFieldText: { fontSize: 15, fontWeight: '600', color: palette.text },
    datePlaceholder: { color: '#81798A', fontWeight: '400' },
    calendarIcon: { width: 24, height: 24, tintColor: palette.primary },
    selectWrap: { marginTop: 14 },
    selectLabel: { fontSize: 12, fontWeight: '700', color: palette.text },
    optional: {
      fontSize: 12,
      lineHeight: 17,
      fontWeight: '600',
      color: palette.muted,
      marginTop: 4,
      marginBottom: 8,
    },
    selectField: {
      minHeight: 56,
      borderRadius: 17,
      borderWidth: 1,
      borderColor: palette.line,
      backgroundColor: '#fff',
      paddingHorizontal: 16,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    selectFieldOpen: {
      borderColor: palette.secondary,
      borderBottomLeftRadius: 8,
      borderBottomRightRadius: 8,
    },
    selectValue: { flex: 1, fontSize: 14, lineHeight: 20, color: palette.text },
    selectChevron: {
      fontSize: 20,
      lineHeight: 20,
      fontWeight: '800',
      color: palette.text,
    },
    selectMenu: {
      marginTop: 6,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: palette.line,
      backgroundColor: '#fff',
      overflow: 'hidden',
    },
    selectOption: {
      minHeight: 50,
      paddingHorizontal: 16,
      flexDirection: 'row',
      alignItems: 'center',
      borderBottomWidth: 1,
      borderBottomColor: palette.line,
    },
    selectOptionOn: { backgroundColor: '#D8C7FA' },
    selectOptionText: {
      flex: 1,
      fontSize: 14,
      lineHeight: 20,
      color: palette.text,
    },
    selectOptionTextOn: { fontWeight: '700', color: palette.primaryDark },
    selectTick: { fontSize: 15, fontWeight: '800', color: palette.primary },
    dateModalBackdrop: {
      flex: 1,
      backgroundColor: 'rgba(32,26,43,0.36)',
      justifyContent: 'flex-end',
      padding: 16,
    },
    dateModal: {
      backgroundColor: '#fff',
      borderRadius: 24,
      paddingHorizontal: 18,
      paddingTop: 20,
      paddingBottom: 14,
      shadowColor: '#201A2B',
      shadowOpacity: 0.18,
      shadowRadius: 24,
      shadowOffset: { width: 0, height: -6 },
    },
    dateModalTitle: {
      fontSize: 18,
      lineHeight: 24,
      fontWeight: '800',
      color: palette.text,
      textAlign: 'center',
    },
    dateModalActions: { flexDirection: 'row', gap: 10, marginTop: 4 },
    dateModalButton: {
      flex: 1,
      minHeight: 48,
      borderRadius: 16,
      alignItems: 'center',
      justifyContent: 'center',
    },
    dateModalCancel: { fontSize: 14, fontWeight: '700', color: palette.muted },
    dateModalDone: { backgroundColor: palette.primary },
    dateModalDoneText: { fontSize: 14, fontWeight: '800', color: '#fff' },
    questionSource: {
      fontSize: 13,
      lineHeight: 19,
      color: palette.muted,
      marginBottom: 4,
    },
  }),
};
