import { palette } from '@/shared/ui/mha-ui';
import { StyleSheet } from 'react-native';
export const s = StyleSheet.create({
  safe: { flex: 1, backgroundColor: '#FFFFFF' },
  content: {
    width: '100%',
    maxWidth: 680,
    alignSelf: 'center',
    paddingHorizontal: 24,
    paddingTop: 20,
    paddingBottom: 116,
  },
  title: {
    fontSize: 25,
    lineHeight: 32,
    fontWeight: '800',
    color: palette.text,
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderBottomColor: palette.line,
  },
  eyebrow: {
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 1,
    color: palette.primary,
    marginBottom: 7,
  },
  heroTitle: { marginBottom: 0 },
  heroLine: {
    minHeight: 33,
    flexDirection: 'row',
    alignItems: 'flex-start',
    flexWrap: 'wrap',
  },
  heroText: {
    fontSize: 27,
    lineHeight: 33,
    fontWeight: '800',
    letterSpacing: -0.55,
    color: palette.text,
  },
  brandWord: { position: 'relative', width: 76, height: 33 },
  powered: {
    fontSize: 13,
    lineHeight: 14,
    fontWeight: '800',
    color: palette.text,
    position: 'absolute',
    left: 22,
    top: 0,
  },
  profile: {
    marginTop: 18,
    borderRadius: 20,
    backgroundColor: '#F3EEFF',
    borderWidth: 1,
    borderColor: '#E3D9F6',
    padding: 18,
    shadowColor: '#5E17EB',
    shadowOpacity: 0.06,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 5 },
    elevation: 2,
  },
  profileTitle: {
    fontSize: 17,
    lineHeight: 23,
    fontWeight: '800',
    color: palette.text,
  },
  updated: { fontSize: 12, lineHeight: 17, color: palette.muted, marginTop: 6 },
  profileInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginTop: 16,
  },
  heart: {
    width: 36,
    fontSize: 30,
    lineHeight: 36,
    color: palette.primary,
    textAlign: 'center',
  },
  profileCopy: { flex: 1, fontSize: 13, lineHeight: 19, color: palette.text },
  profileButton: {
    alignSelf: 'flex-end',
    minHeight: 42,
    borderRadius: 21,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E3D9F6',
    paddingHorizontal: 18,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 14,
  },
  profileButtonText: {
    fontSize: 13,
    fontWeight: '700',
    color: palette.primary,
  },
  quickRow: { flexDirection: 'row', gap: 12, marginTop: 16 },
  quick: {
    flex: 1,
    borderRadius: 18,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E3D9F6',
    paddingHorizontal: 15,
    paddingVertical: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    shadowColor: '#32165C',
    shadowOpacity: 0.06,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  quickPressed: { backgroundColor: '#F3EEFF', transform: [{ scale: 0.98 }] },
  quickText: {
    flex: 1,
    paddingRight: 10,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '800',
    color: palette.text,
  },
  quickArrow: { fontSize: 24, lineHeight: 24, color: palette.primary },
  insights: {
    marginTop: 24,
    backgroundColor: '#F3EEFF',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#E3D9F6',
    padding: 18,
  },
  insightHeading: {
    fontSize: 16,
    lineHeight: 22,
    fontStyle: 'italic',
    fontWeight: '800',
    color: palette.text,
  },
  insightMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    marginTop: 15,
    marginBottom: 2,
  },
  insightLabel: {
    flex: 1,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '600',
    color: palette.text,
  },
  recordCount: {
    fontSize: 11,
    lineHeight: 16,
    fontWeight: '700',
    color: palette.primary,
    backgroundColor: '#D8C7FA',
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  trend: { width: '100%' },
  chart: {
    height: 88,
    position: 'relative',
    marginTop: 10,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#DED5EA',
    borderRadius: 14,
    overflow: 'hidden',
  },
  point: {
    position: 'absolute',
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: palette.secondary,
  },
  pointLast: {
    backgroundColor: palette.primary,
    width: 14,
    height: 14,
    borderRadius: 7,
  },
  number: {
    position: 'absolute',
    fontSize: 10,
    fontWeight: '700',
    color: palette.text,
    left: -1,
    top: -25,
  },
  dateCanvas: { height: 27, position: 'relative' },
  date: {
    position: 'absolute',
    width: 40,
    textAlign: 'center',
    fontSize: 10,
    color: palette.muted,
    top: 7,
  },
  actions: {
    flexDirection: 'row',
    marginTop: 16,
    borderRadius: 14,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#DED5EA',
    backgroundColor: '#FFFFFF',
  },
  action: {
    flex: 1,
    minHeight: 60,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 8,
    paddingVertical: 10,
    alignItems: 'center',
    justifyContent: 'center',
    borderRightWidth: 1,
    borderRightColor: '#DED5EA',
  },
  actionLast: { borderRightWidth: 0 },
  actionText: {
    fontSize: 11,
    lineHeight: 15,
    fontWeight: '700',
    textAlign: 'center',
    color: palette.text,
  },
  sponsor: {
    fontSize: 11,
    lineHeight: 16,
    fontWeight: '600',
    color: palette.muted,
    textAlign: 'center',
    marginTop: 28,
  },
});
