import { useState } from 'react';
import { router, useLocalSearchParams } from 'expo-router';
import { KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { ActionButton, MhaHeader, palette } from '@/components/mha-ui';

const configs:Record<string,{prompt:string;options?:string[];input?:string}>={
  'My Personal Care':{prompt:'Which areas of personal care have been affected?',options:['Washing','Dressing','Sleeping','None of these']},
  'My Social Health':{prompt:'Which areas of your social life have been affected?',options:['Relationships with others','Social life','Travelling','None of these']},
  'My Management':{prompt:'What are you currently using to manage your pain?',options:['Medication','Over-the-counter products','Exercise','Other']},
  'Add a reflection for this week':{prompt:'Add a reflection for this week',input:'Write your reflection'},
  'Check Pain Guide':{prompt:'Pain Guide',options:['Understanding my pain','Talking with my doctor','Managing daily activities','Questions to consider']},
  'Check my health tracking records':{prompt:'My health tracking record',options:['Pain intensity','Movement','Personal care','Social health','Management']},
  'Check my prescriptions':{prompt:'Add prescription',input:'Prescription name, dose and frequency'},
  'Check pain history':{prompt:'Pain intensity',options:['25/05 — 5','01/06 — 5','08/06 — 7']},
  'Prepare for my appointment':{prompt:'Prepare for my appointment',options:['Add appointment details','Explore questions generated for me','Add support person','Review My Plan']},
  'Explore tips':{prompt:'Explore self-management tips for my ongoing pain',options:['Movement','Personal care','Social health','Management']},
};

export default function Detail(){const{title=''}=useLocalSearchParams<{title:string}>(),config=configs[title]??{prompt:title},[selected,setSelected]=useState<string[]>([]),[note,setNote]=useState(''),[saved,setSaved]=useState(false);const toggle=(option:string)=>setSelected(v=>v.includes(option)?v.filter(x=>x!==option):[...v,option]);const canSave=!!note.trim()||selected.length>0||!config.options&&!config.input;if(saved)return <SafeAreaView style={s.safe} edges={['top']}><MhaHeader/><View style={s.complete}><View style={s.check}><Text style={s.checkText}>✓</Text></View><Text style={s.completeTitle}>Saved</Text><Text style={s.completeCopy}>{config.prompt}</Text><ActionButton label="Done" onPress={()=>router.back()}/></View></SafeAreaView>;return <SafeAreaView style={s.safe} edges={['top']}><MhaHeader/><KeyboardAvoidingView style={{flex:1}} behavior={Platform.OS==='ios'?'padding':undefined}><ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled"><Pressable onPress={()=>router.back()} style={s.back}><Text style={s.backText}>‹  Back</Text></Pressable><Text style={s.eyebrow}>MPOWERED HEALTH</Text><Text style={s.title}>{config.prompt}</Text>{config.options?<View style={s.options}>{config.options.map(option=>{const active=selected.includes(option);return <Pressable key={option} accessibilityRole="checkbox" accessibilityState={{checked:active}} onPress={()=>toggle(option)} style={({pressed})=>[s.option,active&&s.optionActive,pressed&&{opacity:.82}]}><Text style={[s.optionText,active&&s.optionTextActive]}>{option}</Text><View style={[s.box,active&&s.boxActive]}><Text style={s.tick}>{active?'✓':''}</Text></View></Pressable>})}</View>:null}{config.input?<TextInput multiline placeholder={config.input} placeholderTextColor="#8B8490" value={note} onChangeText={setNote} style={s.input}/>:null}<View style={s.footer}><ActionButton label="Save" onPress={()=>canSave&&setSaved(true)}/>{!canSave?<Text style={s.hint}>Select an option or enter information to continue.</Text>:null}</View></ScrollView></KeyboardAvoidingView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:palette.background},content:{width:'100%',maxWidth:680,alignSelf:'center',paddingHorizontal:24,paddingTop:4,paddingBottom:120},back:{alignSelf:'flex-start',paddingVertical:18,paddingRight:24},backText:{fontSize:14,fontWeight:'700',color:palette.primary},eyebrow:{fontSize:11,fontWeight:'800',letterSpacing:1.15,color:palette.primary,marginTop:6,marginBottom:9},title:{fontSize:29,lineHeight:36,fontWeight:'800',letterSpacing:-.7,color:palette.text,maxWidth:520},options:{gap:12,marginTop:28},option:{minHeight:64,borderWidth:1,borderColor:palette.line,borderRadius:19,paddingHorizontal:18,paddingVertical:12,flexDirection:'row',alignItems:'center',backgroundColor:'#fff',shadowColor:'#2F174A',shadowOpacity:.035,shadowRadius:8,shadowOffset:{width:0,height:4}},optionActive:{backgroundColor:'#F3EEFF',borderColor:'#BEA1F7'},optionText:{flex:1,fontSize:15,fontWeight:'600',lineHeight:21,color:palette.text},optionTextActive:{color:palette.primaryDark,fontWeight:'700'},box:{width:24,height:24,borderRadius:8,borderWidth:1.5,borderColor:'#B9AFC8',alignItems:'center',justifyContent:'center'},boxActive:{backgroundColor:palette.primary,borderColor:palette.primary},tick:{fontSize:14,fontWeight:'800',color:'#fff'},input:{minHeight:170,marginTop:28,borderWidth:1,borderColor:palette.line,borderRadius:22,backgroundColor:'#fff',padding:18,fontSize:15,lineHeight:22,color:palette.text,textAlignVertical:'top'},footer:{marginTop:32},hint:{fontSize:11,color:palette.muted,textAlign:'center',marginTop:10},complete:{width:'100%',maxWidth:680,alignSelf:'center',flex:1,padding:28,justifyContent:'center',alignItems:'center'},check:{width:76,height:76,borderRadius:38,backgroundColor:'#E1F2EA',alignItems:'center',justifyContent:'center',marginBottom:22},checkText:{fontSize:34,fontWeight:'800',color:'#27705A'},completeTitle:{fontSize:30,fontWeight:'800',color:palette.text},completeCopy:{fontSize:15,lineHeight:22,color:palette.muted,textAlign:'center',marginTop:8,marginBottom:30},});
