import { palette } from '@/shared/ui/mha-ui';
import { StyleSheet } from 'react-native';
export const s = StyleSheet.create({
  detailRow: {
    minHeight: 66,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#E3D9F6',
  },
  detailRowLast: { borderBottomWidth: 0 },
  detailMark: {
    width: 36,
    height: 36,
    borderRadius: 12,
    backgroundColor: '#D8C7FA',
    alignItems: 'center',
    justifyContent: 'center',
  },
  detailMarkText: {
    fontSize: 10,
    fontWeight: '900',
    color: palette.primaryDark,
  },
  detailCopy: { flex: 1 },
  answerHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    marginBottom: 10,
  },
  answerPill: {
    minHeight: 28,
    borderRadius: 14,
    backgroundColor: '#D8C7FA',
    paddingHorizontal: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  answerPillSaved: { backgroundColor: '#E9DEFF' },
  answerLabelSaved: { color: palette.primaryDark },
  editCircle: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#DED5EA',
    alignItems: 'center',
    justifyContent: 'center',
  },
  noQuestions: {
    minHeight: 54,
    marginTop: 10,
    borderRadius: 14,
    backgroundColor: '#F3EEFF',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  noQuestionsText: { fontSize: 13, fontWeight: '600', color: palette.muted },
  answerModalScroll: {
    maxHeight: '82%',
    borderRadius: 22,
    backgroundColor: '#fff',
  },
  answerEyebrow: {
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 1,
    color: palette.primary,
    marginBottom: 8,
  },
  recordChoiceOn: { backgroundColor: '#FCECEF', borderColor: '#E9B7C2' },
  recordChoicePressed: { opacity: 0.82, transform: [{ scale: 0.99 }] },
  micImage: { width: 22, height: 22, tintColor: palette.primary },
  stopIcon: { fontSize: 15, lineHeight: 18, fontWeight: '900', color: '#fff' },
  recordTextOn: { color: palette.error },
  micOn: { backgroundColor: palette.error },
  recordStatus: {
    minHeight: 38,
    marginTop: 8,
    borderRadius: 12,
    backgroundColor: '#FCECEF',
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  liveDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: palette.error,
  },
  recordStatusText: { fontSize: 12, fontWeight: '700', color: palette.error },
  recordStatusSaved: {
    minHeight: 38,
    marginTop: 8,
    borderRadius: 12,
    backgroundColor: '#EDE5FF',
    paddingHorizontal: 12,
    justifyContent: 'center',
  },
  recordSavedText: {
    fontSize: 12,
    fontWeight: '800',
    color: palette.primaryDark,
  },
  modalSecondary: {
    minHeight: 48,
    paddingHorizontal: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalSave: { flex: 1 },
  consentScreen: { flex: 1, backgroundColor: palette.background },
  consentBack: {
    minHeight: 64,
    paddingHorizontal: 24,
    justifyContent: 'center',
  },
  consentContent: {
    width: '100%',
    maxWidth: 680,
    alignSelf: 'center',
    paddingHorizontal: 24,
    paddingTop: 4,
  },
  consentHeading: { marginBottom: 12 },
  consentEyebrow: {
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 1,
    color: palette.primary,
    marginBottom: 6,
  },
  consentTitle: {
    fontSize: 25,
    lineHeight: 31,
    fontWeight: '800',
    letterSpacing: -0.35,
    color: palette.text,
  },
  consentCard: {
    flexShrink: 1,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: palette.line,
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingTop: 7,
    paddingBottom: 10,
  },
  consentFooter: {
    width: '100%',
    maxWidth: 680,
    alignSelf: 'center',
    paddingHorizontal: 24,
    paddingTop: 16,
    paddingBottom: 12,
  },
  signaturePad: {
    height: 96,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#DED5EA',
    backgroundColor: '#F3EEFF',
    overflow: 'hidden',
    position: 'relative',
  },
  signatureHint: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 38,
    textAlign: 'center',
    fontSize: 13,
    color: palette.muted,
  },
  clearSignature: {
    alignSelf: 'flex-end',
    paddingVertical: 3,
    paddingHorizontal: 4,
  },
  clearSignatureText: {
    fontSize: 12,
    fontWeight: '700',
    color: palette.primary,
  },
  step: {
    fontSize: 12,
    lineHeight: 18,
    fontWeight: '800',
    letterSpacing: 0.5,
    color: palette.primary,
    marginTop: 8,
  },
  planFooter: { marginTop: 22 },
  safe: { flex: 1, backgroundColor: palette.background },
  content: {
    width: '100%',
    maxWidth: 680,
    alignSelf: 'center',
    paddingHorizontal: 24,
    paddingTop: 14,
    paddingBottom: 120,
  },
  back: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '700',
    color: palette.primary,
    paddingVertical: 12,
  },
  title: {
    fontSize: 27,
    lineHeight: 34,
    fontWeight: '800',
    letterSpacing: -0.45,
    color: palette.text,
  },
  plan: {
    marginTop: 20,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#E5DFF0',
    borderRadius: 22,
    padding: 18,
    shadowColor: '#32165C',
    shadowOpacity: 0.055,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 5 },
    elevation: 2,
  },
  cardTitle: {
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '800',
    color: palette.text,
  },
  overview: {
    backgroundColor: '#F7F4FC',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#E8E0F3',
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 16,
    marginTop: 14,
  },
  metaLabel: {
    fontSize: 11,
    lineHeight: 16,
    fontWeight: '800',
    color: palette.primaryDark,
    marginTop: 12,
  },
  metaValue: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '600',
    color: palette.text,
    marginTop: 2,
  },
  questionsTitle: {
    fontSize: 17,
    lineHeight: 23,
    fontWeight: '800',
    color: palette.text,
    marginTop: 26,
  },
  consentRow: {
    minHeight: 48,
    borderRadius: 14,
    backgroundColor: '#F3EEFF',
    borderWidth: 1,
    borderColor: 'transparent',
    paddingHorizontal: 13,
    paddingVertical: 9,
    marginTop: 10,
    flexDirection: 'row',
    alignItems: 'center',
  },
  consentRowOn: {
    backgroundColor: '#EDE5FF',
    borderColor: palette.accent,
    shadowColor: palette.primary,
    shadowOpacity: 0.1,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  consentCopy: { flex: 1, paddingRight: 10 },
  consentText: {
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '700',
    color: palette.text,
  },
  consentTextOn: {
    fontSize: 13,
    fontWeight: '800',
    color: palette.primaryDark,
  },
  consentMeta: {
    fontSize: 10,
    lineHeight: 14,
    fontWeight: '600',
    color: palette.muted,
    marginTop: 2,
  },
  check: {
    width: 22,
    height: 22,
    borderRadius: 5,
    borderWidth: 1.5,
    borderColor: palette.muted,
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkOn: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: palette.primary,
    borderColor: palette.primary,
  },
  checkMark: { fontSize: 13, fontWeight: '800', color: '#fff' },
  group: { marginTop: 22, gap: 10 },
  groupTitle: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '800',
    color: palette.primaryDark,
    paddingHorizontal: 2,
  },
  question: {
    minHeight: 104,
    borderRadius: 16,
    backgroundColor: '#F7F4FC',
    borderWidth: 1,
    borderColor: '#E8E0F3',
    padding: 15,
    flexDirection: 'row',
    alignItems: 'flex-start',
    shadowColor: '#32165C',
    shadowOpacity: 0.025,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
  },
  questionCopy: { flex: 1 },
  answerLabel: {
    fontSize: 10,
    lineHeight: 14,
    fontWeight: '800',
    letterSpacing: 0.2,
    color: palette.primary,
    marginBottom: 7,
  },
  questionText: { fontSize: 14, lineHeight: 21, color: palette.text },
  edit: { fontSize: 19, color: palette.primaryDark, marginLeft: 10 },
  modalShade: {
    flex: 1,
    backgroundColor: 'rgba(32,26,43,.35)',
    justifyContent: 'center',
    padding: 18,
  },
  modal: {
    backgroundColor: '#fff',
    borderRadius: 22,
    padding: 20,
    paddingBottom: 18,
  },
  modalQuestion: {
    fontSize: 16,
    lineHeight: 23,
    fontWeight: '700',
    color: palette.text,
    marginBottom: 14,
  },
  answerInput: {
    minHeight: 220,
    maxHeight: 320,
    borderRadius: 14,
    backgroundColor: '#F4F2F7',
    padding: 14,
    fontSize: 14,
    color: palette.text,
    textAlignVertical: 'top',
  },
  recordChoice: {
    minHeight: 60,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginTop: 14,
    borderRadius: 16,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#DED5EA',
    paddingHorizontal: 12,
    paddingVertical: 8,
    shadowColor: '#32165C',
    shadowOpacity: 0.035,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
  },
  mic: {
    width: 42,
    height: 42,
    borderRadius: 14,
    backgroundColor: '#D8C7FA',
    alignItems: 'center',
    justifyContent: 'center',
  },
  micText: { fontSize: 16, color: '#fff' },
  recordText: {
    flex: 1,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '800',
    color: palette.primaryDark,
  },
  modalActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginTop: 20,
  },
  cancel: { fontSize: 14, fontWeight: '700', color: palette.muted },
  ok: { fontSize: 14, fontWeight: '800', color: palette.primary },
  consentModal: { backgroundColor: '#fff', borderRadius: 22, padding: 20 },
  fieldLabel: {
    fontSize: 11,
    lineHeight: 16,
    fontWeight: '700',
    color: palette.text,
    marginTop: 8,
    marginBottom: 4,
  },
  readonly: {
    minHeight: 39,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#DED5EA',
    backgroundColor: '#FAF9FC',
    paddingHorizontal: 14,
    justifyContent: 'center',
  },
  signature: {
    minHeight: 92,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: palette.line,
    backgroundColor: '#F4F2F7',
    padding: 13,
    textAlignVertical: 'top',
  },
  legal: {
    fontSize: 10,
    lineHeight: 14,
    color: palette.muted,
    marginTop: 2,
    paddingHorizontal: 2,
  },
  consentActions: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 18,
    marginTop: 18,
  },
  save: { width: 160 },
});
