/** Defines the colors, spacing, and layout used by form controls. */
import { palette } from '@/shared/ui/mha-ui';
import { StyleSheet } from 'react-native';
export const s = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: palette.background,
  },
  content: {
    width: '100%',
    maxWidth: 680,
    alignSelf: 'center',
    paddingHorizontal: 24,
    paddingTop: 20,
    paddingBottom: 120,
  },
  back: {
    fontSize: 14,
    fontWeight: '700',
    color: palette.primary,
    paddingVertical: 14,
  },
  title: {
    fontSize: 29,
    lineHeight: 35,
    fontWeight: '800',
    letterSpacing: -0.6,
    color: palette.text,
    marginTop: 8,
    marginBottom: 8,
  },
  flowEyebrow: {
    fontSize: 11,
    fontWeight: '800',
    color: palette.primary,
    marginTop: 5,
  },
  copy: {
    fontSize: 15,
    lineHeight: 23,
    color: palette.muted,
    marginTop: 10,
    marginBottom: 16,
  },
  fieldError: { color: palette.error, fontSize: 12, marginTop: 6 },
  fieldWrap: {
    marginTop: 14,
  },
  fieldLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: palette.text,
    marginBottom: 7,
  },
  input: {
    minHeight: 56,
    borderRadius: 17,
    borderWidth: 1,
    borderColor: palette.line,
    backgroundColor: '#fff',
    padding: 15,
    fontSize: 15,
    color: palette.text,
    textAlignVertical: 'top',
  },
  choiceWrap: {
    gap: 12,
    marginVertical: 16,
  },
  choiceTitle: {
    fontSize: 13,
    fontWeight: '800',
    color: palette.text,
    marginBottom: 2,
  },
  choice: {
    minHeight: 60,
    borderWidth: 1,
    borderColor: palette.line,
    borderRadius: 17,
    backgroundColor: '#fff',
    paddingHorizontal: 16,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
  },
  choiceOn: {
    backgroundColor: '#F3EEFF',
    borderColor: '#BEA1F7',
  },
  choiceText: {
    flex: 1,
    fontSize: 14,
    lineHeight: 20,
    color: palette.text,
    paddingRight: 10,
  },
  choiceTextOn: {
    fontWeight: '700',
    color: palette.primaryDark,
  },
  circle: {
    width: 23,
    height: 23,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: '#B9AFC8',
    alignItems: 'center',
    justifyContent: 'center',
  },
  square: {
    width: 23,
    height: 23,
    borderRadius: 7,
    borderWidth: 1.5,
    borderColor: '#B9AFC8',
    alignItems: 'center',
    justifyContent: 'center',
  },
  mark: {
    backgroundColor: palette.primary,
    borderColor: palette.primary,
  },
  tick: {
    fontSize: 12,
    fontWeight: '800',
    color: '#fff',
  },
  footer: {
    marginTop: 32,
  },
  skip: {
    fontSize: 13,
    fontWeight: '700',
    color: palette.primary,
    textAlign: 'center',
    padding: 16,
  },
  required: {
    fontSize: 12,
    fontWeight: '400',
    color: palette.text,
    textAlign: 'center',
    marginTop: 10,
  },
});
